# Generated by Django 5.0.1 on 2024-01-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Hotel Name: ')),
                ('city', models.CharField(max_length=30, verbose_name='City: ')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
